name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hi, Welcome to my Repo! Pleasure to have you here. 
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for the contribution. I will review and take measures accordingly.'
        pr-message: 'Thanks for the contribution. I will review and take measures accordingly.'
